language: node_js
node_js:
  - 12

env:
  - TEST_SUITE:browser
  - TEST_SUITE:server

addons:
  postgresql: 10

services:
  - postgresql
  - redis-server

before_script:
  - cp config/knex.config.js{.example,}
  - psql -c 'create database bughouse_test;' -U postgres
  - NODE_ENV=test yarn migrate

script: "yarn test:$TEST_SUITE"

cache: yarn
