language: node_js
node_js:
  - 10

addons:
  postgresql: "9.6"

services:
  - postgresql
  - redis-server

before_script:
  - cp config/knex.config.js{.example,}
  - psql -c 'create database bughouse_test;' -U postgres
  - NODE_ENV=test yarn migrate

cache: yarn
