language: node_js
node_js:
  - 8

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - cp config/knex.config.js{.example,}
  - psql -c 'create database bughouse_test;' -U postgres

cache: yarn
