version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${USER:-postgres}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - '/var/run/postgresql:/var/run/postgresql'

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
      - 'discovery.type=single-node'
    ports:
      - "9200:9200"
      - "9300:9300"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.2
    volumes:
      - './config/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro'
      - './log:/var/log/bughouse:ro'

  kibana:
    image: kibana:7.6.2
    ports:
      - "5601:5601"

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.6.2
    volumes:
      - './config/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro'
    ports:
      - "8200:8200"
