version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - '/var/run/postgresql:/var/run/postgresql'

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
