filebeat.inputs:
- type: log
  enabled: true
  paths:
    - log/*.log

output.elasticsearch:
  enabled: true
  hosts: ["http://elasticsearch:9200"]

setup.ilm.enabled: auto
setup.ilm.rollover_alias: "bughouse"
